#ifndef REPORT_DESCRIPTOR_H
#define REPORT_DESCRIPTOR_H

#include <stdint.h>
#include "class/hid/hid_device.h"
#include "report_ids.h"

#define REPORT_ID_COUNT (LAST - 1)

#define REPORT_DESC_MODULE_CONNECTED \
    HID_COLLECTION(HID_COLLECTION_LOGICAL),\
        HID_REPORT_ID(REPORT_ID_MODULE_CONNECTED)\
        HID_USAGE_PAGE(HID_USAGE_PAGE_DESKTOP),\
        HID_USAGE(HID_USAGE_DESKTOP_SYSTEM_CONTROL),\
        HID_LOGICAL_MIN(0),\
        HID_LOGICAL_MAX(255),\
        HID_REPORT_COUNT(3),\
        HID_REPORT_SIZE(8),\
        HID_INPUT(HID_DATA | HID_VARIABLE | HID_ABSOLUTE),\
    HID_COLLECTION_END\

#define REPORT_DESC_UID_ITEMS \
    HID_USAGE_PAGE(HID_USAGE_PAGE_DESKTOP),\
    HID_USAGE(HID_USAGE_DESKTOP_SYSTEM_CONTROL),\
    HID_LOGICAL_MIN(0),\
    HID_LOGICAL_MAX(255),\
    HID_REPORT_COUNT(1),\
    HID_REPORT_SIZE(8),\
    HID_INPUT(HID_DATA | HID_VARIABLE | HID_ABSOLUTE)\

#define REPORT_DESC_MODULE_DISCONNECTED \
    HID_COLLECTION(HID_COLLECTION_LOGICAL),\
        HID_REPORT_ID(REPORT_ID_MODULE_DISCONNECTED)\
        REPORT_DESC_UID_ITEMS,\
    HID_COLLECTION_END\

#define REPORT_DESC_DIGITAL_DATA \
    HID_COLLECTION(HID_COLLECTION_PHYSICAL),\
        HID_REPORT_ID(REPORT_ID_DIGITAL_DATA)\
        REPORT_DESC_UID_ITEMS,\
        HID_USAGE_PAGE(HID_USAGE_PAGE_BUTTON),\
        HID_USAGE_MIN(1),\
        HID_USAGE_MAX(1),\
        HID_LOGICAL_MIN(0),\
        HID_LOGICAL_MAX(255),\
        HID_REPORT_COUNT(1),\
        HID_REPORT_SIZE(8),\
        HID_INPUT(HID_DATA | HID_VARIABLE | HID_ABSOLUTE),\
    HID_COLLECTION_END\

#define REPORT_DESC_ANALOG_DATA \
    HID_COLLECTION(HID_COLLECTION_PHYSICAL),\
        HID_REPORT_ID(REPORT_ID_ANALOG_DATA)\
        REPORT_DESC_UID_ITEMS,\
        HID_USAGE_PAGE(HID_USAGE_PAGE_BUTTON),\
        HID_USAGE_MIN(1),\
        HID_USAGE_MAX(4),\
        HID_LOGICAL_MIN(0),\
        HID_LOGICAL_MAX(255),\
        HID_REPORT_COUNT(1),\
        HID_REPORT_SIZE(8),\
        HID_INPUT(HID_DATA | HID_VARIABLE | HID_ABSOLUTE),\
    HID_COLLECTION_END\

#define REPORT_DESC_JOYSTICK_DATA \
    HID_COLLECTION(HID_COLLECTION_PHYSICAL),\
        HID_REPORT_ID(REPORT_ID_JOYSTICK_DATA)\
        REPORT_DESC_UID_ITEMS,\
        HID_USAGE_PAGE(HID_USAGE_PAGE_DESKTOP),\
        HID_USAGE(HID_USAGE_DESKTOP_X),\
        HID_USAGE(HID_USAGE_DESKTOP_Y),\
        HID_LOGICAL_MIN(0),\
        HID_LOGICAL_MAX(255),\
        HID_REPORT_SIZE(8),\
        HID_REPORT_COUNT(3),\
        HID_INPUT(HID_DATA | HID_VARIABLE | HID_ABSOLUTE),\
    HID_COLLECTION_END\

// const uint8_t hid_report[] = REPORT_DESCRIPTOR;
#define REPORT_DESCRIPTOR \
    HID_USAGE_PAGE(HID_USAGE_PAGE_DESKTOP),\
    HID_USAGE(HID_USAGE_DESKTOP_GAMEPAD),\
    HID_COLLECTION(HID_COLLECTION_APPLICATION),\
        REPORT_DESC_MODULE_CONNECTED,\
        REPORT_DESC_MODULE_DISCONNECTED,\
        REPORT_DESC_DIGITAL_DATA,\
        REPORT_DESC_ANALOG_DATA,\
        REPORT_DESC_JOYSTICK_DATA,\
    HID_COLLECTION_END\

#endif